### ISSUE TITLE
Should only support POST, PUT and PATCH verbs for worker endpoints

### ISSUE THREAD

**Issue by rubn-g** [taskforcesh/bullmq-proxy#24]
When a worker with a GET method is added, jobs fail with this error message:
`request with GET/HEAD/OPTIONS method cannot have body`

After checking the file `worker-http-controller.ts` i can see body is always set, no matter which endpoint method is used:
`body: JSON.stringify({ job: job.toJSON(), token }),`

Maybe body shouldn't be set if GET method is used?

**Comment by manast** [comment]
Although the HTTP specification does not prohibit sending a body in a GET call, it may be wise to not allow the GET verb when registering worker endpoints as in your case, for example, your server does not support it. I Will mark this issue as an enhancement.
