### ISSUE TITLE
Timeline? 

### ISSUE THREAD

**Issue by Jss4646** [taskforcesh/bullmq-proxy#6]
Hi! This project looks really cool, and is exactly what I need for a project I am working on. Is there a timeline for when this would be production ready?

**Comment by manast** [comment]
I am currently working on a PR that I think will be quite close to production ready in the sense that it would be quite easy and safe to use, but of course until it has been more battle tested it is impossible to put a production ready label on it. Expect the new PR this week.

**Comment by Jss4646** [comment]
Amazing, thank you!
